#!/bin/bash
#  Script to Re-create tables from Views on Daily basis 
#  Usage : Daily_table_load.sh SID 
#  The script is desgined for Execution in Linux Servers 
#
#
#
#

if [ $# -ne 1] 
  then 
  echo " Script Execution Failed \n SID  DB Name Should be Passed as Argument \n Usage : Daily_table_load.sh SID "
  echo "             "
  exit 1
fi 

##########################Variables for Script Execution ##########################

unset ORACLE_SID
unset ORACLE_HOME 
export ORACLE_SID=$1
export ORACLE_HOME=`cat /etc/oratab |grep -v '#' |grep -i '$1' |cut -d':' -f2`
export PATH=$ORACLE_HOME/bin:$PATH ;
export DTSTRN=`/bin/date +%m%d%y%H%M`

echo " Recreating Tables in DB $1  \n\n RDBMS HOME for DB $1 is $ORACLE_HOME "

####################################################################################

CNTFL=Table_count_Drop_$DT.sql
LOGFL=Drop_create_$DT.log
CRTFL=Table_creae_$DT.sql

echo "Generating sql File to Gather count of Rows in Tables and Dropping Tables \n "
echo "                                       "
$ORACLE_HOME/bin/sqlplus -s /nolog << EOF | awk '!/^Connected\./' > $CNTFL
connect BI/BI
select 'spool Table_count_Drop_$DT.log' from dual ;
set pagesize 0 feed off verify off
select 'set pagesize 0 feed on verify off timing on time on ;' from dual ;
select 'select count(*) as "MQ_ACTIVE_COUNT"  from MQ_ACTIVE_TBL ;' from dual ;
select 'select count(*) as "MQ_DC_COUNT"  from MQ_DC_TBL ;' from dual ;
select 'select count(*) as "ICC_ACTIVE_COUNT"  from ICC_ACTIVE_TBL ;' from dual ;
select 'select count(*) as "ICC_DC_COUNT"  from ICC_DC_TBL ;' from dual ;
select 'drop table MQ_ACTIVE_TBL purge ; ' from dual ; 
select 'drop table MQ_DC_TBL purge ; ' from dual ;
select 'drop table ICC_ACTIVE_TBL purge ; ' from dual ;
select 'drop table ICC_DC_TBL purge ; ' from dual ;
select 'spool off;' from dual ; 
EOF


echo "Generating Sql file to Create Tables from Views \n "
echo "                                  
                 "
$ORACLE_HOME/bin/sqlplus -s /nolog << EOF | awk '!/^Connected\./' > $CRTFL
connect BI/BI
select 'spool Table_create_$DT.log' from dual ;
set pagesize 0 feed on verify off
select 'set pagesize 0 feed on verify off timing on time on ;' from dual ;
select 'create table MQ_ACTIVE_TBL as select * from MQ_ACTIVE_CUST_PRODUCT_LTD\@"BI_IMCLDB";' from dual ;
select 'create table MQ_DC_TBL as select * from MQ_DC_CUST_PRODUCT_LTD\@"BI_IMCLDB";' from dual ;
select 'create table ICC_ACTIVE_TBL as select * from ICC_ACTIVE_CUSTOMER_PRODUCTS\@"BI_GILPRD";' from dual ;
select 'create table ICC_DC_TBL as select * from ICC_DC_CUSTOMER_PRODUCTS\@"BI_GILPRD";' from dual ;
select 'spool off;' from dual ;  
EOF


###echo "Gathering table Count ,Dropping Tables "
###$ORACLE_HOME/bin/sqlplus -s /nolog << EOF | awk '!/^Connected\./' > $LOGFL
###connect / as sysdba
###@$CNTFL
###@$CRTFL
###exit;
###EOF

exit 
