#!/bin/bash
#  Script       : scheduled_job_stats.sh 
#  Description  : Script to identify Disabled or Broken  Scheduler Jobs
#  Instructions : Script should be executed in below format 
#                  sh scheduled_job_stats.sh DBANME 
#
################## Parameter For Script ######################

if [ $# -lt 1 ]
  then 
  echo " Script has been executed with wrong no of arguments "
  echo " Execute Script in below format " 
  echo " sh $0 DBNAME" 
  exit 1
fi 


unset ORACLE_SID
unset ORACLE_HOME 
export sname=`hostname`
export DT=`date +%d%m%Y%H`
export db=$1
export ORACLE_HOME=`cat /etc/oratab|grep $db|cut -d: -f2`
export ORACLE_SID=`ps -ef|grep smon|grep -v 'ASM|grep'|grep $db|awk '{print $8}'|cut -d_ -f3`
export PATH=$ORACLE_HOME/bin:$PATH ;
export MAIL_LIST="user@Mailid.com"

################## Program part ################################

echo "
set verify off heading off feed off echo off termout on trimspool on 
set lines 550 pages 0
set colsep '||'
col job_name for a25
col state for a25
col ENABLED for a25
spool job_check_${DT}.log
select job_name,state,enabled from dba_scheduler_jobs where state not in ('SCHEDULED','RUNNING','COMPLETED','SUCCEEDED') ;
spool off;
exit ; " > job_check_$DT.sql

$ORACLE_HOME/bin/sqlplus -s /nolog <<EOF   |grep -v 'Connected' >>/dev/null
connect / as sysdba
@job_check_$DT.sql
exit ;
EOF

if [ -e job_check_${DT}.log ]
  then 
    export JOB_ERROR_MSG=" Scheduler Jobs  are Broken or Disabled in Database $db on server $sname \n\n Refer the Log file attached in for the Job Details   "  
	echo -e $JOB_ERROR_MSG | /bin/mailx -a job_check_${DT}.log -s "Job Status for Database $db at $DT" $MAIL_LIST
  else 
    echo "JOB status is Normal for Database $db on server $sname" 
fi 
	
exit ; 
